### PR TITLE
Tweak style on mobile menu

### PR DESCRIPTION
**Pull request by katiemthom**

### CODE REVIEW

**Comment by katiemthom** [comment]
Note -- this actually breaks the close button on the mobile menu. I'm not sure why yet, but I'll work on fixing that... If any front end person wants to look at it too that's good :)

**Comment by katiemthom** [comment]
Actually, the close button on the mobile menu is already broken. I'll file a separate issue to fix that.

**Comment by mbyczkowski** [comment]
@katiemthom I merged the other PR (#71 I think) and this one probably needs a rebase now.

**Comment by mbyczkowski** [comment]
ok, I've rebased this PR. I think the position of close button was fixed in the other now, so only the color change applies here.

**Comment by katiemthom** [comment]
Thanks!

**Pull request merged**
