### PR TITLE
Add secondary header style

### PR DESCRIPTION
**Pull request by katiemthom**
-Equivalent to "SUBHEADING or non-caps" in Zeplin.
-Related to Issue #1

### CODE REVIEW

**Comment by mbyczkowski** [comment]
I think that could work. We could also try to ride on Foundation framework as much as we can. They have `subheader` class for this. http://foundation.zurb.com/sites/docs/typography-helpers.html#subheader

**Comment by mbyczkowski** [comment]
Some of this can be customized in Foundation settings (e.g. here https://github.com/mbyczkowski/lacocina/blob/master/app/assets/stylesheets/_settings.scss#L171-L181), but for some we'll probably have to override for certain pages.

Thanks for getting the first PR in for this project! 👏

**Comment by mbyczkowski** [comment]
@katiemthom is this ready to go or is it your WIP PR for style change?

**Comment by katiemthom** [comment]
It's fine to go! I just wanted to make it available so we can use it as needed by the designs.

**Pull request merged**
